//
//  LearnStore.swift — the fifteen minutes, as a state machine.
//
//  Mirrors DigestStore: an @MainActor ObservableObject that owns the network
//  calls and publishes what the views draw. The difference is that this one
//  has a sequence rather than a poll loop, so the phase is the state and every
//  transition goes through one of the methods below.
//
//      topic ──START──▶ timer ──DONE/expiry──▶ explaining ──SUBMIT──▶ grading
//        ▲                │                        ▲                     │
//        └────CANCEL──────┘                        └───error─────────────┤
//        └──────────────────────NEW────────────────────────── result ◀───┘
//
//  Two rules the rest of this file exists to keep:
//
//  **The countdown is a deadline, not a counter.** `deadline` is an absolute
//  Date and `remaining` is derived from it on every tick. Decrementing a stored
//  number instead loses time whenever the app is busy, the display sleeps or
//  the machine suspends — and it loses it silently, so a fifteen-minute timer
//  quietly runs eighteen and the only symptom is that the session felt long.
//
//  **The explanation outlives everything except an explicit new session.** It
//  survives a grading failure, a tab switch, and the panel being resized. It is
//  fifteen minutes of work and it is the one thing here that cannot be
//  regenerated by asking the backend again.
//

import AppKit
import Foundation
import SwiftUI

enum LearnPhase: Equatable {
    case topic
    case timer
    case explaining
    case grading
    case result
    case stats
}

@MainActor
final class LearnStore: ObservableObject {

    // MARK: Published state

    @Published private(set) var phase: LearnPhase = .topic
    @Published private(set) var topic: LearnTopic?
    @Published private(set) var session: LearnSession?
    @Published private(set) var grade: Grade?
    @Published private(set) var stats: LearnStats?

    /// Seconds left. Derived from `deadline` on every tick — never decremented.
    @Published private(set) var remaining: TimeInterval = LearnStore.sessionDuration
    @Published private(set) var paused = false

    /// Bound straight into the TextEditor, so it is the one piece of state the
    /// view owns rather than the store. Not private(set) for that reason.
    ///
    /// Every keystroke here also lands in UserDefaults — see `saveDraft()`.
    /// This is the only state in the app worth surviving a crash for: the
    /// digest re-fetches, the streak re-fetches, but fifteen minutes of
    /// typing does not exist anywhere else.
    @Published var explanation = "" {
        didSet { saveDraft() }
    }

    @Published private(set) var busy = false
    @Published private(set) var lastError: String?

    // MARK: Configuration

    // nonisolated because these are immutable and read from default arguments
    // and from view bodies. Without it, `posed`'s defaults touch main-actor
    // state from a nonisolated context — a warning in Swift 5, an error in 6.
    nonisolated static let sessionDuration: TimeInterval = 15 * 60

    /// 10 Hz. The border trace moves 0.1% of its length per tick at this rate,
    /// which is smooth, and the countdown label only changes once a second
    /// anyway. Fast enough to look continuous, slow enough to be free.
    nonisolated private static let tickInterval: TimeInterval = 0.1

    /// The border trace animates across one tick, so it slides rather than
    /// stepping. Matching tickInterval exactly is what keeps it continuous —
    /// a longer duration would still be catching up when the next tick lands.
    nonisolated static let tickAnimation: TimeInterval = tickInterval

    private(set) var client: LearnClient
    private var deadline: Date?
    private var tickTask: Task<Void, Never>?

    /// False only for `posed()`. A snapshot store must neither overwrite a
    /// real in-progress draft with its fixture text nor load one into a
    /// picture that is supposed to be reproducible.
    private let draftPersistenceEnabled: Bool

    init(baseURL: URL, draftPersistenceEnabled: Bool = true) {
        self.client = LearnClient(baseURL: baseURL)
        self.draftPersistenceEnabled = draftPersistenceEnabled
        if draftPersistenceEnabled { restoreDraft() }
    }

    func setBaseURL(_ url: URL) {
        client = LearnClient(baseURL: url)
    }

    // MARK: - Derived

    /// 0 at the start, 1 when the time is up. The border trace reads this.
    var elapsedFraction: Double {
        let done = Self.sessionDuration - remaining
        return min(max(done / Self.sessionDuration, 0), 1)
    }

    /// "14:32". Always mm:ss, and never negative — expiry moves the phase on,
    /// but a tick can land between zero and that happening.
    var clockText: String {
        let whole = Int(max(remaining, 0).rounded(.up))
        return String(format: "%d:%02d", whole / 60, whole % 60)
    }

    var difficultyText: String { (topic?.difficulty ?? "").uppercased() }

    // MARK: - Drawing a topic

    /// Called when the tab is opened with nothing in hand, and by NEW.
    func drawTopicIfNeeded() async {
        guard topic == nil, !busy else { return }
        await drawTopic()
    }

    func drawTopic() async {
        busy = true
        lastError = nil
        do {
            topic = try await client.drawTopic()
        } catch {
            lastError = error.localizedDescription
        }
        busy = false
    }

    // MARK: - The session

    func start() async {
        guard let topic, !busy else { return }
        busy = true
        lastError = nil
        do {
            session = try await client.startSession(topicID: topic.topicID)
            // The clock starts when the server has actually opened the session,
            // not when the button was pressed — otherwise a slow call silently
            // eats seconds off the fifteen minutes.
            deadline = Date().addingTimeInterval(Self.sessionDuration)
            remaining = Self.sessionDuration
            paused = false
            phase = .timer
            startTicking()
        } catch {
            lastError = error.localizedDescription
        }
        busy = false
    }

    func pause() {
        guard phase == .timer, !paused else { return }
        paused = true
        stopTicking()
        // `remaining` is already correct from the last tick and `deadline` is
        // rebuilt from it on resume, so there is nothing else to store.
    }

    func resume() {
        guard phase == .timer, paused else { return }
        paused = false
        deadline = Date().addingTimeInterval(remaining)
        startTicking()
    }

    /// Abandon the session and go back to the topic.
    ///
    /// The row the backend opened is simply never graded. That is not a leak:
    /// /learn/stats counts grades rather than sessions, so an abandoned one
    /// affects nothing except having put its topic on cooldown — which is
    /// correct, since it was drawn and shown.
    func cancel() {
        stopTicking()
        session = nil
        deadline = nil
        paused = false
        remaining = Self.sessionDuration
        explanation = ""
        grade = nil
        lastError = nil
        phase = .topic
        clearDraft()
    }

    /// DONE, or the clock reaching zero. Both land in the same place.
    func finishEarly() {
        guard phase == .timer else { return }
        stopTicking()
        paused = false
        phase = .explaining
        // "Funk" is the closest thing in the system sound set to a low buzz
        // rather than an alert — Basso and Sosumi read as errors, this one
        // just says the timer's done.
        NSSound(named: "Funk")?.play()
    }

    // MARK: - Grading

    func submit() async {
        guard phase == .explaining, let session, !busy else { return }
        guard !explanation.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            lastError = "Nothing to grade yet."
            return
        }

        busy = true
        lastError = nil
        phase = .grading

        do {
            grade = try await client.grade(sessionID: session.sessionID,
                                           explanation: explanation)
            phase = .result
            clearDraft()
            // The streak has just changed; fetch it so opening STATS is instant
            // rather than showing the previous numbers for a beat.
            await loadStats()
        } catch {
            // Back to the editor with the text still in it. This is the path
            // that matters most in the whole file: a 502 here must cost a
            // button press, not the session.
            lastError = error.localizedDescription
            phase = .explaining
        }
        busy = false
    }

    /// After a result: clear everything and draw the next topic.
    func newSession() async {
        session = nil
        deadline = nil
        remaining = Self.sessionDuration
        paused = false
        explanation = ""
        grade = nil
        topic = nil
        phase = .topic
        clearDraft()
        await drawTopic()
    }

    // MARK: - Stats

    func loadStats() async {
        do {
            stats = try await client.fetchStats()
        } catch {
            lastError = error.localizedDescription
        }
    }

    func showStats() async {
        phase = .stats
        await loadStats()
    }

    /// Leaving stats returns to whatever the session was doing, which is the
    /// topic screen unless one is in flight.
    func leaveStats() {
        guard phase == .stats else { return }
        phase = session == nil ? .topic : (grade == nil ? .explaining : .result)
    }

    // MARK: - Posing, for the snapshot harness
    //
    // The five screens are only reachable by living through a session, which
    // makes them exactly the thing a still is worth having of. This puts a
    // store straight into a phase so Snapshot can render it. Nothing in the
    // running app calls it, and it deliberately starts no timer.

    static func posed(
        phase: LearnPhase,
        topic: LearnTopic? = nil,
        remaining: TimeInterval = LearnStore.sessionDuration,
        paused: Bool = false,
        explanation: String = "",
        grade: Grade? = nil,
        stats: LearnStats? = nil,
        error: String? = nil
    ) -> LearnStore {
        let store = LearnStore(baseURL: URL(string: "http://127.0.0.1:8010")!,
                                draftPersistenceEnabled: false)
        store.phase = phase
        store.topic = topic
        store.remaining = remaining
        store.paused = paused
        store.explanation = explanation
        store.grade = grade
        store.stats = stats
        store.lastError = error
        return store
    }

    // MARK: - Crash recovery
    //
    // The watchdog LaunchAgent (see desktop/Makefile) restarts this app
    // within seconds of any crash or kill. A fresh process means a fresh
    // LearnStore, so without this, that restart is exactly as destructive to
    // fifteen minutes of typing as the crash was. UserDefaults survives the
    // process dying — it's written through to disk continuously, not only on
    // a clean quit — which is the property that matters here.
    //
    // Deliberately narrow: only explanation, topic and session are saved.
    // Not the countdown — by the time there's anything in `explanation` the
    // timer has already finished (see `finishEarly`), so there is never a
    // live deadline to restore alongside it.

    private struct Draft: Codable {
        let topic: LearnTopic
        let session: LearnSession
        let explanation: String
    }

    private static let draftKey = "learnDraft"

    private func saveDraft() {
        guard draftPersistenceEnabled, let topic, let session else { return }
        let draft = Draft(topic: topic, session: session, explanation: explanation)
        guard let data = try? JSONEncoder().encode(draft) else { return }
        UserDefaults.standard.set(data, forKey: Self.draftKey)
    }

    private func restoreDraft() {
        guard let data = UserDefaults.standard.data(forKey: Self.draftKey),
              let draft = try? JSONDecoder().decode(Draft.self, from: data)
        else { return }
        topic = draft.topic
        session = draft.session
        explanation = draft.explanation
        // Not .grading: if the crash landed mid-submit, whether the backend
        // ever saw that call is unknown. Landing in .explaining puts Submit
        // back in front of the user rather than silently retrying — at worst
        // a 409 from the guard `record_grade` already has, at best the text
        // that was about to be lost is one button press from being graded.
        phase = .explaining
    }

    private func clearDraft() {
        UserDefaults.standard.removeObject(forKey: Self.draftKey)
    }

    // MARK: - Ticking

    private func startTicking() {
        stopTicking()
        tickTask = Task { [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: .seconds(Self.tickInterval))
                guard let self else { return }
                if self.tick() { return }
            }
        }
    }

    private func stopTicking() {
        tickTask?.cancel()
        tickTask = nil
    }

    /// Returns true when the clock has run out and the loop should stop.
    private func tick() -> Bool {
        guard let deadline, phase == .timer, !paused else { return true }
        remaining = deadline.timeIntervalSinceNow
        if remaining <= 0 {
            remaining = 0
            finishEarly()
            return true
        }
        return false
    }
}
